### ISSUE TITLE
Enhancement: Repository Creation/Checkout

### ISSUE THREAD

**Issue by iksiddhanthrao** [G-Node/GinUI#87]
This is about an error that pops up when you try to create a new repository with an existing repository's name.  

It would be best if I illustrate this by showing what exactly happens. 

I had created a repository named Tutorial1 which I had been using regularly. Now, I intend to create a new repository titled Tutorial2, but lets say by accident I type in "Tutorial1". The error message as indicated in image 1 pops up. 

![sc1](https://user-images.githubusercontent.com/37540700/38867896-9c07bb16-4245-11e8-9006-4fed78a7aed9.PNG)

I quickly realise that I had keyed in the wrong repository name and set onto create Tutorial2.

![sc2](https://user-images.githubusercontent.com/37540700/38867894-9a28f59e-4245-11e8-9ecc-cef88ebfc379.PNG)

While you notice that the field "Name" is updated, the Mountpoint directory and Checkout directory is not accordingly updated nor reset. The directory pathways are the same as for Tutorial1 and the previous error pops up again.

![sc3](https://user-images.githubusercontent.com/37540700/38867892-9911e09e-4245-11e8-834b-08a39eb6f68f.PNG)

This might confuse some users and I felt it would be great if the checkout directory is updated accordingly when the name is switched. 

I must mention that even if a typo is made and immediately corrected (before clicking on okay to create/checkout ), the mountpoint/checkout directories are not updated.

**Comment by achilleas-k** [comment]
Thanks for the suggestion and the issue. I think this is a bit tricky because there may be cases where you want them to differ and if the application insists on automatically changing one to match the other might be annoying, after the initial typing. However, I understand your point too. I can imagine one solution would be a warning on screen (perhaps a little note next to the fields) showing that the last element of the mountpoint differs from the last element of the data directory. That way if you really want them to be named differently you can ignore the note and continue.

I'll keep this issue open and think about it some more.

**Comment by JiriVanek** [comment]
Similar problem is while you try to checkout repoA and Checkout and mount directory are prefilled with name of repoA and then you change name of repository to repoB checkout you you get this error 
![image](https://user-images.githubusercontent.com/6449276/51754314-44b27f80-20bc-11e9-8bc8-b6d5be4f1b1f.png)
That creates mount point to non existing repository with name repoA and the repository is downloaded to folder with actual repository name repoB

**Comment by achilleas-k** [comment]
Fixed in #93.
